# Generated by Django 5.0.7 on 2025-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='selected_option',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
