# Generated by Django 5.1.6 on 2025-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_flashcard_flashcardquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardquestions',
            name='answer',
            field=models.CharField(max_length=1023),
        ),
    ]
