# Generated by Django 5.0.7 on 2024-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='submitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
