# Generated by Django 5.0.7 on 2024-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignments_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
