# Generated by Django 5.0.7 on 2024-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignments_assignment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='assignment_number',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
